// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorApp.Models
{
    public partial class GetAllSkillsStudentResult
    {
        public int Studentid { get; set; }
        public int Skillid { get; set; }
        public string Skillname { get; set; }
    }
}
