// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorApp.Models
{
    public partial class GetSkillByIdResult
    {
        public int StudentId { get; set; }
        public int SkillId { get; set; }
    }
}
